"""Scaffold a kernel project from a flashinfer-bench definition.

Everything kernel-specific is derived from the definition JSON — the reference
implementation, the stub signature, and the I/O tables in AGENTS.md. Everything
language-specific comes from a profile in assets/lang/. Nothing is hand-transcribed,
because a wrong shape in AGENTS.md misleads the agent for an entire run.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

ASSETS = Path(__file__).parent / "assets"

# Language profile -> (flashinfer-bench BuildSpec language, source directory).
# These differ for CuTeDSL: it is Python-JIT so it packs with the triton builder,
# but lives in its own folder so the agent never confuses the two.
BUILD = {
    "triton": ("triton", "triton"),
    "cuda": ("cuda", "cuda"),
    "cutedsl": ("triton", "cutedsl"),
}


def languages() -> list[str]:
    return sorted(p.stem for p in (ASSETS / "lang").glob("*.md"))


def _table(spec: dict, title: str, note: str = "") -> str:
    lines = [f"### {title}{note}", "", "| name | shape | dtype |", "|---|---|---|"]
    for name, s in spec.items():
        shape = s.get("shape")
        shape = "scalar" if not shape else "[" + ", ".join(str(x) for x in shape) + "]"
        lines.append(f"| `{name}` | `{shape}` | {s.get('dtype', '?')} |")
    return "\n".join(lines)


def _kernel_section(defn: dict, source_dir: str, kernel_file: str, baseline_file: str) -> str:
    parts = [
        "## This kernel",
        "",
        f"**Definition:** `{defn['name']}`",
        "",
        defn.get("description", "").strip(),
        "",
        f"**You edit:** `solution/{source_dir}/{kernel_file}` — entry point `kernel`",
        f"**Reference:** `solution/{source_dir}/{baseline_file}` — read for numerical semantics",
        "",
        _table(defn.get("inputs", {}), "Inputs"),
        "",
        _table(
            defn.get("outputs", {}),
            "Outputs",
            " (DPS — pre-allocated and passed in; never allocate these inside the kernel)",
        ),
    ]

    axes = defn.get("axes") or {}
    if axes:
        rows = ["", "### Axes", "", "| axis | kind | detail |", "|---|---|---|"]
        for name, a in axes.items():
            kind = a.get("type", "?")
            detail = (a.get("description") or "").strip()
            if kind == "const":
                fixed = f"always {a.get('value')}"
                detail = f"{fixed} — {detail}" if detail else fixed
            rows.append(f"| `{name}` | {kind} | {detail} |")
        parts.append("\n".join(rows))

    constraints = defn.get("constraints") or []
    if constraints:
        parts.append("\n### Constraints\n\n" + "\n".join(f"- `{c}`" for c in constraints))

    return "\n".join(parts) + "\n"


def _stub(defn: dict) -> str:
    args = list(defn.get("inputs", {})) + list(defn.get("outputs", {}))
    return (
        f'"""Kernel under optimization: {defn["name"]}.\n\n'
        f"{defn.get('description', '').strip()}\n\n"
        "Outputs are destination-passing: write into them, do not allocate.\n"
        '"""\n\n\n'
        f"def kernel({', '.join(args)}):\n"
        '    raise NotImplementedError("implement the fused kernel")\n'
    )


CONFIG = """\
# Generated by `kopt init`. Kernel + backend settings for kbench.

[kernel]
definition = "{definition}"
language = "{language}"      # build toolchain{lang_note}
source_dir = "{source_dir}"
entry_point = "{kernel_file}::kernel"

[remote]
backend = "{backend}"   # local | modal | fal   (override: KBENCH_BACKEND)
gpu = "{gpu}"
gpu_count = 1
timeout_s = 1800

[remote.image]
base = "flashinfer/flashinfer-ci-cu132:latest"
apt = ["git", "wget", "build-essential", "cmake"]
# cupti-python is required for accurate GPU timing; without it the timer falls back
# to CUDA events and over-reports latency by launch overhead (~2-4us per call).
pip = ["huggingface_hub", "cupti-python"]
run = [
  "pip install --force-reinstall --upgrade git+https://github.com/flashinfer-ai/flashinfer-bench.git@main",
]

[remote.image.env]
TORCH_EXTENSIONS_DIR = "/results/torch_ext_cache"
# This image's Triton ships without `triton.backends` entry-point metadata, so default
# discovery finds 0 backends -> "0 active drivers". Force in-tree directory scan.
TRITON_BACKENDS_IN_TREE = "1"

[remote.data]
path = "/data"                    # mount point inside the container (fal: /data/<subdir>)
modal_volume = "flashinfer-trace"
local_path = "~/flashinfer-trace"

[bench]
warmup_runs = 3
iterations = 100
num_trials = 5
profile_baseline = false
"""


def _git_init(project: Path) -> None:
    """Make the project its own repo.

    AGENTS.md tells the agent to commit after each logged experiment. Without a repo
    here, `git commit` walks up to whatever repo contains the project and commits
    unrelated work — so the scaffold owns its own history.
    """
    (project / ".gitignore").write_text(".kopt/\n__pycache__/\n*.log\nresults.json\n")
    ident = ["-c", "user.email=kopt@localhost", "-c", "user.name=kopt"]
    try:
        for cmd in (
            ["git", "init", "-q"],
            ["git", "add", "-A"],
            ["git", *ident, "commit", "-q", "-m", "scaffold"],
        ):
            subprocess.run(cmd, cwd=project, check=True, capture_output=True)
    except (OSError, subprocess.CalledProcessError) as exc:
        print(f"  warning: could not init git repo ({exc}); agent commits may escape")


def init(
    project: Path,
    definition_json: Path,
    language: str = "triton",
    backend: str = "modal",
    gpu: str = "B200",
    force: bool = False,
) -> Path:
    if language not in languages():
        raise SystemExit(f"unknown language {language!r}; have: {', '.join(languages())}")
    if project.exists() and any(project.iterdir()) and not force:
        raise SystemExit(f"{project} exists and is not empty (use --force)")

    defn = json.loads(Path(definition_json).read_text())
    if "reference" not in defn:
        raise SystemExit(f"{definition_json} has no `reference` — not a usable definition")

    build_language, source_dir = BUILD.get(language, (language, language))
    kernel_file, baseline_file = "solution_fused.py", "solution_baseline.py"

    omp = project / ".omp"
    src = project / "solution" / source_dir
    experiments = project / "experiments"
    for d in (omp, src, experiments):
        d.mkdir(parents=True, exist_ok=True)

    # Seed the index files. The optimize skill reads both on its first step, so
    # without them every fresh run opens with two failed reads.
    (experiments / "summary.md").write_text(
        "# Experiment index\n\n"
        "| Exp | Date | Description | Latency | Ref | Pass | Backend | Notes |\n"
        "|---|---|---|---|---|---|---|---|\n"
    )
    (experiments / "LESSONS.md").write_text(
        "# Lessons\n\n"
        "Durable cross-experiment findings. Append when a lesson recurs. Remove entries\n"
        "that later turn out to be wrong — a stale lesson blocks a good idea forever.\n"
    )

    # AGENTS.md = generic core + language profile + generated kernel facts
    (omp / "AGENTS.md").write_text(
        (ASSETS / "core.md").read_text().rstrip()
        + "\n\n"
        + (ASSETS / "lang" / f"{language}.md").read_text().rstrip()
        + "\n\n"
        + _kernel_section(defn, source_dir, kernel_file, baseline_file)
    )

    shutil.copy(ASSETS / "config.yml", omp / "config.yml")
    for kind in ("skills", "agents"):
        shutil.copytree(ASSETS / kind, omp / kind, dirs_exist_ok=True)

    (src / baseline_file).write_text(defn["reference"])
    (src / kernel_file).write_text(_stub(defn))

    (project / "config.toml").write_text(
        CONFIG.format(
            definition=defn["name"],
            language=build_language,
            lang_note=(
                f" — sources are `{language}`, which packs with the"
                f" {build_language} builder"
                if build_language != language
                else ""
            ),
            source_dir=source_dir,
            kernel_file=kernel_file,
            backend=backend,
            gpu=gpu,
        )
    )
    _git_init(project)
    return project
